<?php

/**
 * This is the model base class for the table "role".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Role".
 *
 * Columns in table "role" available as properties of the model,
 * followed by relations of table "role" available as properties of the model.
 *
 * @property integer $intRoleID
 * @property string $varName
 *
 * @property User[] $users
 */
abstract class BaseRole extends GxActiveRecord{
	/**
	 * @param string $className
	 *
	 * @return CActiveRecord
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string
	 */
	public function tableName()
	{
		return 'role';
	}

	/**
	 * @param int $n
	 *
	 * @return string
	 */
	public static function label($n = 1)
	{
		return Yii::t('app', 'Role|Roles', $n);
	}

	/**
	 * @return array|string
	 */
	public static function representingColumn()
	{
		return 'varName';
	}

	/**
	 * @return array
	 */
	public function rules()
	{
		return array(
			array('varName', 'required'),
			array('varName', 'length', 'max'=>50),
			array('intRoleID, varName', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array
	 */
	public function relations()
	{
		return array(
			'users' => array(self::HAS_MANY, 'User', 'intRoleID'),
		);
	}

	/**
	 * @return array
	 */
	public function pivotModels()
	{
		return array(
		);
	}

	/**
	 * @return array
	 */
	public function attributeLabels()
	{
		return array(
			'intRoleID' => Yii::t('app', 'Int Role'),
			'varName' => Yii::t('app', 'Var Name'),
			'users' => null,
		);
	}

	/**
	 * @return CActiveDataProvider
	 */
	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('intRoleID', $this->intRoleID);
		$criteria->compare('varName', $this->varName, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}